import type { Metadata } from "next";
import {  JetBrains_Mono } from "next/font/google";
import "./globals.scss";
import Navbar from "@/Components/Navbar/Navbar";
import { ThemeProvider } from "./context/themeProvider";

const jetMono = JetBrains_Mono({
  variable: "--font-jetBrain-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Regis Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  var esposa = "naly"
  return (
    <html lang="en">
      <body className={`${jetMono.variable}`}>
        <div style={{ display: "flex"}}>
          <Navbar />
          <ThemeProvider>{children}</ThemeProvider>
        </div>
      </body>
    </html>
  );
}
