import type { Metadata } from "next";
import {  JetBrains_Mono } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/common/Navbar/Navbar";
import { ThemeProvider } from "./context/themeProvider";
import Image from "next/image";
import styles from "./page.module.css";
import Footer from "@/components/common/Footer";

const jetMono = JetBrains_Mono({
  variable: "--font-jetBrain-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Regis Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${jetMono.variable}`}>
          <ThemeProvider>
            <Navbar />
            {children}
            <Footer />
          </ThemeProvider>
      </body>
    </html>
  );
}
